// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "DataClient": DataClient Resource Client
//
// Command:
// $ goagen
// --design=DataClient/design
// --out=$(GOPATH)\src\DataClient
// --version=v1.3.1

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
)

// AddDataClientPath computes a request path to the add action of DataClient.
func AddDataClientPath(hash string, privateKey string) string {
	param0 := hash
	param1 := privateKey

	return fmt.Sprintf("/data/add/%s/%s", param0, param1)
}

// add data hash
func (c *Client) AddDataClient(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewAddDataClientRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewAddDataClientRequest create the request corresponding to the add action endpoint of the DataClient resource.
func (c *Client) NewAddDataClientRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// AgreeDataClientPath computes a request path to the agree action of DataClient.
func AgreeDataClientPath(eTHKey string, requestID int) string {
	param0 := eTHKey
	param1 := strconv.Itoa(requestID)

	return fmt.Sprintf("/data/agree/%s/%s", param0, param1)
}

// agree data request for request [ID]
func (c *Client) AgreeDataClient(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewAgreeDataClientRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewAgreeDataClientRequest create the request corresponding to the agree action endpoint of the DataClient resource.
func (c *Client) NewAgreeDataClientRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// AskComputingDataClientPath computes a request path to the askComputing action of DataClient.
func AskComputingDataClientPath(hash string, eTHKey string, requestID int) string {
	param0 := hash
	param1 := eTHKey
	param2 := strconv.Itoa(requestID)

	return fmt.Sprintf("/data/askComputing/%s/%s/%s", param0, param1, param2)
}

// ask for computing for [request_id] on computing resourse[hash]
func (c *Client) AskComputingDataClient(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewAskComputingDataClientRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewAskComputingDataClientRequest create the request corresponding to the askComputing action endpoint of the DataClient resource.
func (c *Client) NewAskComputingDataClientRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// DelDataClientPath computes a request path to the del action of DataClient.
func DelDataClientPath(hash string, privateKey string) string {
	param0 := hash
	param1 := privateKey

	return fmt.Sprintf("/data/del/%s/%s", param0, param1)
}

// delete data hash
func (c *Client) DelDataClient(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewDelDataClientRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewDelDataClientRequest create the request corresponding to the del action endpoint of the DataClient resource.
func (c *Client) NewDelDataClientRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// UploadDataDataClientPath computes a request path to the uploadData action of DataClient.
func UploadDataDataClientPath(hash string, eTHKey string, requestID int) string {
	param0 := hash
	param1 := eTHKey
	param2 := strconv.Itoa(requestID)

	return fmt.Sprintf("/data/upload/%s/%s/%s", param0, param1, param2)
}

// upload encrypted data[hash] for [request_id]
func (c *Client) UploadDataDataClient(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewUploadDataDataClientRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewUploadDataDataClientRequest create the request corresponding to the uploadData action endpoint of the DataClient resource.
func (c *Client) NewUploadDataDataClientRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
