// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "DataClient": Application Contexts
//
// Command:
// $ goagen
// --design=DataClient/design
// --out=$(GOPATH)\src\DataClient
// --version=v1.3.1

package app

import (
	"context"
	"github.com/goadesign/goa"
	"net/http"
	"strconv"
)

// AddDataClientContext provides the DataClient add action context.
type AddDataClientContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	Hash       string
	PrivateKey string
}

// NewAddDataClientContext parses the incoming request URL and body, performs validations and creates the
// context used by the DataClient controller add action.
func NewAddDataClientContext(ctx context.Context, r *http.Request, service *goa.Service) (*AddDataClientContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := AddDataClientContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramHash := req.Params["hash"]
	if len(paramHash) > 0 {
		rawHash := paramHash[0]
		rctx.Hash = rawHash
	}
	paramPrivateKey := req.Params["private_key"]
	if len(paramPrivateKey) > 0 {
		rawPrivateKey := paramPrivateKey[0]
		rctx.PrivateKey = rawPrivateKey
	}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *AddDataClientContext) OK(resp []byte) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "plain/text")
	}
	ctx.ResponseData.WriteHeader(200)
	_, err := ctx.ResponseData.Write(resp)
	return err
}

// BadRequest sends a HTTP response with status code 400.
func (ctx *AddDataClientContext) BadRequest(r error) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 400, r)
}

// InternalServerError sends a HTTP response with status code 500.
func (ctx *AddDataClientContext) InternalServerError(r error) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 500, r)
}

// AgreeDataClientContext provides the DataClient agree action context.
type AgreeDataClientContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	ETHKey    string
	RequestID int
}

// NewAgreeDataClientContext parses the incoming request URL and body, performs validations and creates the
// context used by the DataClient controller agree action.
func NewAgreeDataClientContext(ctx context.Context, r *http.Request, service *goa.Service) (*AgreeDataClientContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := AgreeDataClientContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramETHKey := req.Params["ETH_key"]
	if len(paramETHKey) > 0 {
		rawETHKey := paramETHKey[0]
		rctx.ETHKey = rawETHKey
	}
	paramRequestID := req.Params["request_id"]
	if len(paramRequestID) > 0 {
		rawRequestID := paramRequestID[0]
		if requestID, err2 := strconv.Atoi(rawRequestID); err2 == nil {
			rctx.RequestID = requestID
		} else {
			err = goa.MergeErrors(err, goa.InvalidParamTypeError("request_id", rawRequestID, "integer"))
		}
	}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *AgreeDataClientContext) OK(resp []byte) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "plain/text")
	}
	ctx.ResponseData.WriteHeader(200)
	_, err := ctx.ResponseData.Write(resp)
	return err
}

// BadRequest sends a HTTP response with status code 400.
func (ctx *AgreeDataClientContext) BadRequest(r error) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 400, r)
}

// InternalServerError sends a HTTP response with status code 500.
func (ctx *AgreeDataClientContext) InternalServerError(r error) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 500, r)
}

// AskComputingDataClientContext provides the DataClient askComputing action context.
type AskComputingDataClientContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	ETHKey    string
	Hash      string
	RequestID int
}

// NewAskComputingDataClientContext parses the incoming request URL and body, performs validations and creates the
// context used by the DataClient controller askComputing action.
func NewAskComputingDataClientContext(ctx context.Context, r *http.Request, service *goa.Service) (*AskComputingDataClientContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := AskComputingDataClientContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramETHKey := req.Params["ETH_key"]
	if len(paramETHKey) > 0 {
		rawETHKey := paramETHKey[0]
		rctx.ETHKey = rawETHKey
	}
	paramHash := req.Params["hash"]
	if len(paramHash) > 0 {
		rawHash := paramHash[0]
		rctx.Hash = rawHash
	}
	paramRequestID := req.Params["request_id"]
	if len(paramRequestID) > 0 {
		rawRequestID := paramRequestID[0]
		if requestID, err2 := strconv.Atoi(rawRequestID); err2 == nil {
			rctx.RequestID = requestID
		} else {
			err = goa.MergeErrors(err, goa.InvalidParamTypeError("request_id", rawRequestID, "integer"))
		}
	}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *AskComputingDataClientContext) OK(resp []byte) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "plain/text")
	}
	ctx.ResponseData.WriteHeader(200)
	_, err := ctx.ResponseData.Write(resp)
	return err
}

// BadRequest sends a HTTP response with status code 400.
func (ctx *AskComputingDataClientContext) BadRequest(r error) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 400, r)
}

// InternalServerError sends a HTTP response with status code 500.
func (ctx *AskComputingDataClientContext) InternalServerError(r error) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 500, r)
}

// DelDataClientContext provides the DataClient del action context.
type DelDataClientContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	Hash       string
	PrivateKey string
}

// NewDelDataClientContext parses the incoming request URL and body, performs validations and creates the
// context used by the DataClient controller del action.
func NewDelDataClientContext(ctx context.Context, r *http.Request, service *goa.Service) (*DelDataClientContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := DelDataClientContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramHash := req.Params["hash"]
	if len(paramHash) > 0 {
		rawHash := paramHash[0]
		rctx.Hash = rawHash
	}
	paramPrivateKey := req.Params["private_key"]
	if len(paramPrivateKey) > 0 {
		rawPrivateKey := paramPrivateKey[0]
		rctx.PrivateKey = rawPrivateKey
	}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *DelDataClientContext) OK(resp []byte) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "plain/text")
	}
	ctx.ResponseData.WriteHeader(200)
	_, err := ctx.ResponseData.Write(resp)
	return err
}

// BadRequest sends a HTTP response with status code 400.
func (ctx *DelDataClientContext) BadRequest(r error) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 400, r)
}

// InternalServerError sends a HTTP response with status code 500.
func (ctx *DelDataClientContext) InternalServerError(r error) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 500, r)
}

// UploadDataDataClientContext provides the DataClient uploadData action context.
type UploadDataDataClientContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	ETHKey    string
	Hash      string
	RequestID int
}

// NewUploadDataDataClientContext parses the incoming request URL and body, performs validations and creates the
// context used by the DataClient controller uploadData action.
func NewUploadDataDataClientContext(ctx context.Context, r *http.Request, service *goa.Service) (*UploadDataDataClientContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := UploadDataDataClientContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramETHKey := req.Params["ETH_key"]
	if len(paramETHKey) > 0 {
		rawETHKey := paramETHKey[0]
		rctx.ETHKey = rawETHKey
	}
	paramHash := req.Params["hash"]
	if len(paramHash) > 0 {
		rawHash := paramHash[0]
		rctx.Hash = rawHash
	}
	paramRequestID := req.Params["request_id"]
	if len(paramRequestID) > 0 {
		rawRequestID := paramRequestID[0]
		if requestID, err2 := strconv.Atoi(rawRequestID); err2 == nil {
			rctx.RequestID = requestID
		} else {
			err = goa.MergeErrors(err, goa.InvalidParamTypeError("request_id", rawRequestID, "integer"))
		}
	}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *UploadDataDataClientContext) OK(resp []byte) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "plain/text")
	}
	ctx.ResponseData.WriteHeader(200)
	_, err := ctx.ResponseData.Write(resp)
	return err
}

// BadRequest sends a HTTP response with status code 400.
func (ctx *UploadDataDataClientContext) BadRequest(r error) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 400, r)
}

// InternalServerError sends a HTTP response with status code 500.
func (ctx *UploadDataDataClientContext) InternalServerError(r error) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 500, r)
}
