// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "DataClient": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=DataClient/design
// --out=$(GOPATH)\src\DataClient
// --version=v1.3.1

package app
