// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "Data Client": swagger-ui TestHelpers
//
// Command:
// $ goagen
// --design=DataClient/design
// --out=$(GOPATH)\src\DataClient
// --version=v1.3.1

package test
